FROM alpine:3.13 as dbhash-build
RUN apk add build-base tcl
# https://www.sqlite.org/src/tarball/sqlite.tar.gz?r=release 
RUN mkdir -p /src && wget -O - https://www.sqlite.org/src/tarball/sqlite.tar.gz?r=version-3.38.2 | tar zxf - -C /src
WORKDIR /src/sqlite
RUN ./configure && make dbhash


FROM golang:1.16-alpine

ENV CGO_ENABLED=0
RUN apk add --no-cache git

COPY --from=dbhash-build /src/sqlite/dbhash /usr/local/bin/

RUN addgroup -g 1000 -S app && adduser -u 1000 -S app -D -G app
USER app

WORKDIR /go/server/

COPY go.mod go.sum ./
# RUN go mod download
RUN go mod graph | awk '{if ($1 !~ "@") print $2}' | xargs go get

COPY . .

EXPOSE 3000
CMD ["go", "run", "cmd/main.go", "serve"]
