FROM alpine:3.13 as dbhash-build
RUN apk add build-base tcl
# https://www.sqlite.org/src/tarball/sqlite.tar.gz?r=release 
RUN mkdir -p /src && wget -O - https://www.sqlite.org/src/tarball/sqlite.tar.gz?r=version-3.38.2 | tar zxf - -C /src
WORKDIR /src/sqlite
RUN ./configure && make dbhash


FROM golang:1.18-alpine

ENV USERNAME=app
ENV GROUP=app
ENV UID=1000
ENV GID=1000

ENV CGO_ENABLED=0
RUN apk add --no-cache git

COPY --from=dbhash-build /src/sqlite/dbhash /usr/local/bin/

RUN addgroup -g "$GID" -S "$GROUP" && adduser -S -u "$UID" -D -G "$GROUP" "$USERNAME"
USER ${USERNAME}

WORKDIR /go/server/

COPY go.mod go.sum ./
RUN go mod download

COPY ./docker/start-dev.sh /usr/local/bin/

EXPOSE 3000
CMD ["start-dev.sh"]
