FROM alpine:3.13 as dbhash-build
RUN apk add build-base tcl
# https://www.sqlite.org/src/tarball/sqlite.tar.gz?r=release 
RUN mkdir -p /src && wget -O - https://www.sqlite.org/src/tarball/sqlite.tar.gz?r=version-3.38.2 | tar zxf - -C /src
WORKDIR /src/sqlite
RUN ./configure && make dbhash


FROM golang:1.18-alpine as build
RUN apk add --no-cache git
WORKDIR /go/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /go/bin/gisquick cmd/main.go


FROM alpine:latest

ENV USERNAME=app
ENV GROUP=app
ENV UID=1000
ENV GID=1000

# USER nonroot:nonroot
# COPY --from=build --chown=nonroot:nonroot /go/bin/app /app
RUN addgroup -g "$GID" -S "$GROUP" && adduser -S -u "$UID" -D -G "$GROUP" "$USERNAME"

COPY --from=dbhash-build /src/sqlite/dbhash /usr/local/bin/

WORKDIR /app
COPY --from=build /go/src/app/templates ./templates
COPY --from=build /go/bin/gisquick /usr/local/bin/

USER ${USERNAME}
EXPOSE 3000
# ENTRYPOINT ["gisquick"]
CMD ["gisquick", "serve"]
